Sprint 2
IvanofSA/middle.messenger.praktikum.yandex pull request #2
Opened 2021-07-29 21:58 UTC by IvanofSA

2021-07-30 21:13 UTC, nickchamel requested changes
Привет. В целом все отлично! Молодец, отписал тебе рекомендации в комментариях. Но работу вынужден вернуть, так как не доделана. По заданию все-таки должна работать валидация везде. И страница с чатами тоже уже вроде должна быть сделана. И разберись, пожалуйста, с тестами, некоторые у тебя не проходят.

2021-07-30 21:13 UTC, nickchamel commented on README.md
> +npm run lint — запуск линтеров
Когда отправляешь работу на проверку, убедись, что в README на ветке `main` есть ссылка на текущий PR, который нужно проверять

2021-07-30 21:13 UTC, nickchamel commented on src/components/button/button.scss
> +    background-color: #3353f3;
все цвета лучше выносить в переменные и держать отдельно

2021-07-30 21:13 UTC, nickchamel commented on src/components/channel/channel.ts
> +        span.channel__missed= missed`;
Было бы неплохо темплейты привести к одному виду

2021-07-30 21:13 UTC, nickchamel commented on src/components/input/input.ts
> +          this.props.value = element.value;
Лучше не мутировать пропсу напрямую, а через setProps, а вообще я не могу понять в чем прикол) ты присваиваешь тоже самое значение

2021-07-30 21:13 UTC, nickchamel commented on src/pages/chat/chat.model.ts
> +  children?: { [key: string]: HTMLElement };
можно вынести в глобальный тип чилдренов

2021-07-30 21:13 UTC, nickchamel commented on src/pages/chat/chat.scss
> +      background: url("data:image/svg+xml,%3Csvg width='6' height='10' viewBox='0 0 6 10' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M1 9L5 5L1 1' stroke='%23999999'/%3E%3C/svg%3E%0A
Лучше делать по другому.
Для ознакомления https://stackoverflow.com/questions/27077874/the-approaches-to-using-svg-images

2021-07-30 21:13 UTC, nickchamel commented on src/pages/profile/index.pug
> +        //.profile__back.back
Видимо можно удалить

2021-07-30 21:13 UTC, nickchamel commented on src/pages/profile/profile.ts
> +    return element as HTMLElement;
логику по вставке компонента лучше бы вынести на уровень выше, там где ты создаешь экземпляр этого класса. Грубо говоря, компонент не должен знать куда себя рендерить. Он может быть отрендерен где угодно, кем угодно, тут конечно страница, которая более ни кем рендериться не будет, но все же по хорошему лучше так не делать. В дальнейшем будет роутер, это будет его задача.
У тебя как раз в profile/index.ts идет создание - туда лучше поместить логику по вставке, а вот темплейт оттуда как раз лучше убрать и не передавать его в пропсах. В других компонентах у тебя ведь по другому сделано. Темплейт меняться не будет, лучше его в пропсах не прокидывать

2021-07-30 21:13 UTC, nickchamel commented on src/pages/profileEdit/profileEdit.ts
> +import {getData} from "../../utils/getData";
неплохо было бы придерживаться одного стиля написания `{ getData }`

2021-07-30 21:13 UTC, nickchamel commented on src/pages/signup/signup.ts
> +export default class SignUp extends Block {
отступ пропустил

2021-07-30 21:13 UTC, nickchamel commented on src/pages/signup/signup.ts
> +          /*ToDo не очень догнал как провалидировать при клике по человечески и в других формах*/
в курсе нет про это чтоли? Валидация нужна по заданию.
Ты здесь получил данные с формы и проводишь с ними манипуляции по проверке удовлетворяет ли каждое значение какому либо условию.
Например есть функция
`export const isRequired = value => !!value`
ты можешь через нее прогнать значение и если вернет false, а значение не должно быть пустым, значит показывать пользователю соответствующее сообщение.
И так далее, можно проверять на кол-во символов, на соответствие регулярному выражение и тд
Так же ты можешь при создании инпута прокинуть через пропсы массив таких функций, и потом по нему проходить и генерировать какое-то итоговое сообщение об ошибке, например, что `Это поле обязательно`, потом сделать setProps с этими ошибками и отобразить их в шаблоне

2021-07-30 21:13 UTC, nickchamel commented on src/utils/HTTP.ts
> +      }
ты можешь вынести отсюда логику по queryString в метод get, а сюда передавать уже готовый url

2021-07-30 21:13 UTC, nickchamel commented on src/utils/createInputs.ts
> +// }
если не нужно, то лучше удалить и не засорять код

2021-07-30 21:13 UTC, nickchamel commented on src/utils/getData.ts
> +};
Советую посмореть в сторону FormData https://learn.javascript.ru/formdata

2021-07-31 06:47 UTC, IvanofSA commented
> Привет. В целом все отлично! Молодец, отписал тебе рекомендации в комментариях. Но работу вынужден вернуть, так как не доделана. По заданию все-таки должна работать валидация везде. И страница с чатами тоже уже вроде должна быть сделана. И разберись, пожалуйста, с тестами, некоторые у тебя не проходят.

Привет! По странице с чатами не понял, она же есть или там что то не доделано?

2021-07-31 06:50 UTC, IvanofSA commented on src/components/channel/channel.ts
> +        span.channel__missed= missed`;
Тут тоже не понял? Можешь плиз по подробнее, что ты имеешь ввиду ?

2021-07-31 13:21 UTC, nickchamel commented
> > Привет. В целом все отлично! Молодец, отписал тебе рекомендации в комментариях. Но работу вынужден вернуть, так как не доделана. По заданию все-таки должна работать валидация везде. И страница с чатами тоже уже вроде должна быть сделана. И разберись, пожалуйста, с тестами, некоторые у тебя не проходят.
> 
> Привет! По странице с чатами не понял, она же есть или там что то не доделано?

![image](https://user-images.githubusercontent.com/28347933/127741177-698531a2-e11d-4858-a85d-34954b06c156.png)

2021-07-31 13:23 UTC, nickchamel commented on src/components/channel/channel.ts
> +        span.channel__missed= missed`;
Я имею ввиду стилизацию кода, когда пишешь темплейты - перенос кавычек, отступы.. чтобы было в едином стиле во всех компонентах

2021-07-31 16:41 UTC, nickchamel commented
Хорошо! Работа принята, только должно быть не `какая то ошибка`, а конкретный текст, в зависимости от того, какая валидация не прошла. И ты должен учесть что валидаций на одном поле может быть несколько, я тебе потому и говорил про массив функций. Например email должен быть: обязательным и соответствовать регулярке...
Успехов в след. спринте.

2021-08-05 19:42 UTC, merged