sprint 3
IvanofSA/middle.messenger.praktikum.yandex pull request #3
Opened 2021-08-13 15:25 UTC by IvanofSA

2021-08-14 18:07 UTC, nickchamel requested changes
Привет. В целом все хорошо, молодец! Но работу пока возвращаю:
1. Проверь нетлифай - судя по всему там сейчас 2 спринт.
2. Тесты. Они в этом спринте по заданию, нужно доделать этот момент
3. https://github.com/IvanofSA/middle.messenger.praktikum.yandex/runs/3323451011?check_suite_focus=true все чеки и тесты должны проходить, ну вообщем-то после первых двух пунктов этот должен будет заработать.
Рекомендации по коду оставил. Удачи!

2021-08-14 18:07 UTC, nickchamel commented on netlify.toml
> + status = 200
А зачем это?)
Чтоб произошел этот редирект, нужно слать запрос на `https://6105680321527d0398fb3f5f--quizzical-gates-1efd18.netlify.app/api/...`, то есть туда, где у тебя нетлифай развернут, а ты сюда запросы не посышаешь...

2021-08-14 18:07 UTC, nickchamel commented on src/api/authApi.ts
> +const authApi = new HTTPTransport(host);
С помощью одного из принципов ООП - наследования, можно лаконичней и мастабируемей писать код.
В данном случае можно сделать класс BaseApi, в котором будет создаваться экземпляр HTTPTransport.
А все твои апи будут от этого класса наследоваться, таким образом у всех будет HTTPTransport и не нужно будет повторять код и создавать лишние экземпляры транспорта.
Так же в BaseApi можно сделать baseUrl `https://ya-praktikum.tech/api/v2/`, а эндпоинт `auth`, например через конструктор прокидывать

2021-08-14 18:07 UTC, nickchamel commented on src/api/chatsApi.ts
> +  getChatUsersToken(id: number) {
На самом деле возвращаемые функциями значения тоже можно типизировать. Чем больше кода покрыто типами, тем меньше ошибок в будущем и вообще проще разработка

2021-08-14 18:07 UTC, nickchamel commented on src/api/chatsApi.ts
> +      data: JSON.stringify({ users: [userId], chatId }),
для массива с айдишниками правильней будет задать имя, например `usersIds`

2021-08-14 18:07 UTC, nickchamel commented on src/api/webSocket.ts
> +    this.callBack = callBack;
Для того чтобы сделать синглтон-инстанс достаточно просто написать `export default new WebSocketMessage()`.
А вообще - тут у тебя в конструктор есть параметры, то есть ты можешь создавать разные инстансы с разными параметрами, но при этом это у тебя всеравно синглтон. Несостыковочка получается

2021-08-14 18:07 UTC, nickchamel commented on src/api/webSocket.ts
> +    console.log(`Код: ${event.code} | Причина: ${event.reason}`);
Если код работает, то можно удалить все логи отсюда

2021-08-14 18:07 UTC, nickchamel commented on src/pages/chats/chats.ts
> +            const id = Number(e.currentTarget.getAttribute("data-id"));
атрибуты с префиксом `data-` досутпны в `element.dataset`, то есть для удобства можно так `e.currentTarget.dataset.id`

2021-08-14 18:07 UTC, nickchamel commented on src/pages/chats/chats.ts
> +              });
везде, где может произойти выброс исключения, нужно его обрабатывать. В данном случае, поскольку экземпляры http транспорта могут зарезолвить ошибку, после каждого вызова апи нужно дописывать `.catch` блок.

2021-08-14 18:07 UTC, nickchamel commented on src/pages/chats/chats.ts
> +            this.tooltip.classList.add("show");
то есть если `.closest(".messages__head")` будет, то возьмется `querySelector(".messages__tooltip")`, а иначе будет `null`, то есть и дальше должно быть `this.tooltip?.classList.add("show");`
По логике так

2021-08-14 18:07 UTC, nickchamel commented on src/pages/chats/chats.ts
> +                      console.log("add user");
Лучше не называть так переменные, в код приходиться вчитываться, если это массив юзеров, значит лучше пусть будет `users[0]`. Логи можно убрать

2021-08-14 18:07 UTC, nickchamel commented on src/pages/chats/chats.ts
> +            console.log("click add home-page__form-search");
Вообщем везде по коду

2021-08-14 18:07 UTC, nickchamel commented on src/pages/chats/chats.ts
> +    new ChatsApi().getChats().then((data) => {
Все апи должны быть синглтонами, там ничего не меняется от экземпляра к экземпляру.
```
export default new ChatsApi()
```
```
import ChatsApi from '...'
...
ChatsApi.getChats()...
```

2021-08-14 18:07 UTC, nickchamel commented on src/pages/chats/chats.ts
> +      const result = JSON.parse(data);
логику по парсингу респонса лучше выносить в http класс

2021-08-14 18:07 UTC, nickchamel commented on src/pages/chats/chats.ts
> +      });
вот здесь есть catch. В остальных местах это тоже необходимо

2021-08-14 18:07 UTC, nickchamel commented on src/utils/HTTP.ts
> +        isGet && Boolean(data) ? url + queryStringify(data) : url
если логика по `queryStringify ` присутсвует только для get, то лучше имеено туда ее и вынести, а здесь будет всегда уже готовый url

2021-08-20 13:26 UTC, nickchamel requested changes
Привет. Спасибо за доработки, к сожалению саму работу все еще не могу проверить.
Какой адрес сайта на нетлифае?
В ридми ты изменил на
![image](https://user-images.githubusercontent.com/28347933/130239656-d7804fb6-619f-48c4-b643-0da00775786f.png)
Интеграция говорит о другом
![image](https://user-images.githubusercontent.com/28347933/130239733-082a806d-52c2-4d45-b10d-c56b8eb26589.png)
В любом случае и там и там я даже залогиниться не могу:
![image](https://user-images.githubusercontent.com/28347933/130239795-01ab8589-838b-449e-8f24-d564652c7a17.png)
При клике ничего не происходит.
Так же валидация некорректно работает (ошибка продолжает показываться, хотя емейл валидный), на другом поле вообще нет валидации. Вот вырезка из заданий (2 спринт)
![image](https://user-images.githubusercontent.com/28347933/130240099-c197920e-79cb-4139-bd01-f3e28c398945.png)
Страница регистрации не работает.
![image](https://user-images.githubusercontent.com/28347933/130240026-a9f39b03-7359-4e70-9a38-77de61385e2e.png)

2021-08-20 13:26 UTC, nickchamel commented on src/components/profileEdit/profileEdit.ts
> +    return compile(template)(this.props);
метод рендер может отрабатывать множество раз за время жизненного цикла компонента, а `compile(template)` всегда возвращает один и тот же результат, поэтому ее можно вынести наверх перед объявлением класса, чтобы на каждом ререндере не проделывать эту работу

2021-08-20 13:26 UTC, nickchamel commented on src/utils/validate.ts
> +    if ({}.hasOwnProperty.call(valids, key)) {
так у тебя вроде выше написана `for (const key in valids) {`
Получается что условие всегда выполнится и в нем нет необходимости

2021-08-21 09:15 UTC, IvanofSA reviewed
> Привет. Спасибо за доработки, к сожалению саму работу все еще не могу проверить.
> Какой адрес сайта на нетлифае?
> В ридми ты изменил на
> ![image](https://user-images.githubusercontent.com/28347933/130239656-d7804fb6-619f-48c4-b643-0da00775786f.png)
> Интеграция говорит о другом
> ![image](https://user-images.githubusercontent.com/28347933/130239733-082a806d-52c2-4d45-b10d-c56b8eb26589.png)
> В любом случае и там и там я даже залогиниться не могу:
> ![image](https://user-images.githubusercontent.com/28347933/130239795-01ab8589-838b-449e-8f24-d564652c7a17.png)
> При клике ничего не происходит.
> Так же валидация некорректно работает (ошибка продолжает показываться, хотя емейл валидный), на другом поле вообще нет валидации. Вот вырезка из заданий (2 спринт)
> ![image](https://user-images.githubusercontent.com/28347933/130240099-c197920e-79cb-4139-bd01-f3e28c398945.png)
> Страница регистрации не работает.
> ![image](https://user-images.githubusercontent.com/28347933/130240026-a9f39b03-7359-4e70-9a38-77de61385e2e.png)

Привет! Там же написано ЛОГИН, а ты туда почту пишешь

2021-08-21 09:15 UTC, IvanofSA commented on src/pages/chats/chats.ts
> +              });
Привет! Разве она на уровне хттптранспорта не выпадет ?

2021-08-21 09:15 UTC, IvanofSA commented on src/pages/chats/chats.ts
> +                      console.log("add user");
вы имеете ввиду result ?

2021-08-21 10:42 UTC, nickchamel commented
> Привет! Там же написано ЛОГИН, а ты туда почту пишешь

Хмм сори, я может за прошлый спринт привык писать почту!
Но я тож не могу зайти, запрос проходит, редиректа нет.
![image](https://user-images.githubusercontent.com/28347933/130319246-88a0d005-5084-4f1f-b478-a76f5172ef10.png)

2021-08-23 12:25 UTC, nickchamel commented on src/pages/chats/chats.ts
> +                      console.log("add user");
ага

2021-08-23 12:32 UTC, nickchamel commented on src/pages/chats/chats.ts
> +              });
ChatsApi().getChatUsers возвращает результат вызова http.get, а http.get возвращает результат вызова http.request, а http.request можешь выкинуть ошибку (reject) - значит она пойдет выше по вызовам, а поскольку до этого (http.get, ChatsApi.getChatUsers) нет await'ов и try/catch'ей или then/catch, там просто идет возврат промисов, значит ошибка упадет здесь и если ее не обработать - она повалит приложение

2021-08-23 12:39 UTC, nickchamel commented
Привет. Спасибо за доработки! Посмотрел работу. В целом все хорошо, но нашел несколько критичных моментов. Давай их поправим и все будет отлично.
1. После успешного логина не происходит редиректа, лучше будет если пользователь попадет на /messenger
2. Сообщения в чатах не отправляются
3. При выходе идет редирект на логин (что верно), и тут же на /messenger, где не показываются чаты и в принципе нельзя ничего сделать потому что юзер не авторизован
3. Аватар в профиле не показывается (вернее показывается дефолтный). Не сильно критично но лучше поправить

2021-08-23 15:00 UTC, nickchamel approved these changes
Заметил у тебя еще баг - при отправке сообщения в чат, после перезагрузки страницы оно появляется в другом чате.
Все основное вроде работает. Работу принимаю. Удачи в дальшнейшем

2021-08-23 15:00 UTC, nickchamel commented on src/utils/HTTPTransport/HTTPTransport.ts
> +          }
Не знаю для чего ты это сделал, но если ты хотел решить вопрос с обработчиками ошибок, то это не решает эту проблему.
У тебя reject остается в этом методе ниже. Этот метод может завершить промис реджектом - значит там где  ты его будешь вызывать управление не перейдет в блок .then. А блока catch у тебя нет

2021-08-23 15:22 UTC, IvanofSA commented on src/utils/HTTPTransport/HTTPTransport.ts
> +          }
я типо чекую можно ли респонс парсить, а то там ошибка сыпалась

2021-08-23 15:28 UTC, nickchamel commented on src/utils/HTTPTransport/HTTPTransport.ts
> +          }
а, понял

2021-08-23 15:32 UTC, merged